name: Build & Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: 'Environment to deploy'
        required: true
        default: 'production'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build frontend + wasm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        working-directory: ./www
        run: npm ci

      - name: Build wasm (release, bundler target)
        working-directory: ./www
        run: |
          wasm-pack build --target bundler --out-dir ./www/pkg --release

      - name: Build webpack (production)
        working-directory: ./www
        run: npx webpack --config webpack.config.js --mode production

      - name: Prepare dist for deployment (add .nojekyll)
        run: echo "" > ./www/dist/.nojekyll

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./www/dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
